all_permissions: {  }
can_view_comments: {  }
can_approve_comments: {  }
can_unapprove_comments: {  }
can_reply_to_comments: {  }
can_edit_comments: {  }
can_report_as_spam: {  }
can_report_as_ham: {  }
can_remove_comments: {  }
