guards:
  - Stillat\Meerkat\Core\Guard\Providers\AkismetSpamGuard
  - Stillat\Meerkat\Core\Guard\Providers\WordFilterSpamGuard
auto_publish: false
auto_publish_authenticated_users: false
only_accept_comments_from_authenticated_users: false
automatically_close_comments: 0
guard_check_all_providers: false
guard_unpublish_on_guard_failure: false
auto_check_spam: true
auto_delete_spam: false
auto_submit_results: false
